### ISSUE TITLE
I segnali progressivamente scompaiono

### ISSUE THREAD

**Issue by fbedussi** [fbedussi/off-grid#1]
Dopo essere usciti dallo schermo i segnali vengono fatti ripartire dal centro.

Al momento però con il passare dei cicli progressivamente scompaiono.

Il desiderata è che il numero di segnali rimanga costante. 

Il problema probabilmente è collegato con il fatto che alcuni segnali rimangono bloccati al centro e dipende forse dalle componenti velocità sui 2 assi (vx e vy).

**Comment by MaxArt2501** [comment]
Il problema è [quello](https://github.com/fbedussi/off-grid/blob/master/plugins.js#L413) infatti:

```javascript
// plugins.js:413
function internal_move(sprite) {
  sprite.x += sprite.vx | 0;
  sprite.y += sprite.vy | 0;
}
```
Sostanzialmente, se `vx` e/o `vy` sono minori di 1 in valore assoluto, non si muovono.
Vista così però passare alle coordinate radiali non mi pare risolva granché: anche se la velocità è maggiore di 1, potrebbe capitare che le componenti lungo gli assi siano minori di 1.

In sostanza: bisogna aumentare drasticamente la dpi del campo di gioco, per cui 1 px = 100 unità o una roba del genere.

**Comment by fbedussi** [comment]
O generiamo vx e vy in modo che siano maggiori di 1 oppure modifichiamo noi a mano sprite.x e sprite.y il che tra l'altro ci evita di chiamare il metodo `move` che è in plugin.js e quindi di improtare quel file. 

Nel caso dei device già cambiamo noi a mano x e y.

**Comment by MaxArt2501** [comment]
Direi che la seconda strada è migliore, perché imporre che `vx` e `vy` siano maggiori di 1 di fatto impedisce traiettorie quasi orizzontali o quasi verticali.

Immagino che quel ` | 0` sia stato messo per questioni di velocità, ma non penso che avremo problemi di performance 😀

**Comment by fbedussi** [comment]
Confermo: facendo
`signal.x += signal.vx;signal.y += signal.vy;`
invece di `move` il problema rientra
